plugins:
  chatbot_enabled:
    default: true
    client: true
  chatbot_permitted_in_private_messages:
    default: true
    client: true
  chatbot_permitted_in_chat:
    default: true
    client: true
  chatbot_high_trust_groups:
    client: false
    default: ''
    type: group_list
    list_type: compact
  chatbot_medium_trust_groups:
    client: false
    default: ''
    type: group_list
    list_type: compact
  chatbot_low_trust_groups:
    client: false
    default: ''
    type: group_list
    list_type: compact
  chatbot_bot_type_high_trust:
    default: RAG
    client: false
    type: enum
    choices:
      - basic
      - RAG
  chatbot_open_ai_model_high_trust:
    client: false
    type: enum
    default: gpt-3.5-turbo
    choices:
      - gpt-3.5-turbo
      - gpt-4
      - gpt-4-32k
      - gpt-4-turbo-preview
  chatbot_open_ai_model_custom_high_trust:
    default: false
    client: false
  chatbot_open_ai_model_custom_name_high_trust:
    default: ''
    client: false
  chatbot_open_ai_model_custom_url_high_trust:
    client: false
    default: ''
  chatbot_bot_type_medium_trust:
    default: basic
    client: false
    type: enum
    choices:
      - basic
      - RAG
  chatbot_open_ai_model_medium_trust:
    client: false
    type: enum
    default: gpt-3.5-turbo
    choices:
      - gpt-3.5-turbo
      - gpt-4
      - gpt-4-32k
      - gpt-4-turbo-preview
  chatbot_open_ai_model_custom_medium_trust:
    default: false
    client: false
  chatbot_open_ai_model_custom_name_medium_trust:
    default: ''
    client: false
  chatbot_open_ai_model_custom_url_medium_trust:
    client: false
    default: ''
  chatbot_bot_type_low_trust:
    default: basic
    client: false
    type: enum
    choices:
      - basic
      - RAG
  chatbot_open_ai_model_low_trust:
    client: false
    type: enum
    default: gpt-3.5-turbo
    choices:
      - gpt-3.5-turbo
      - gpt-4
      - gpt-4-32k
      - gpt-4-turbo-preview
  chatbot_open_ai_model_custom_low_trust:
    default: false
    client: false
  chatbot_open_ai_model_custom_name_low_trust:
    default: ''
    client: false
  chatbot_open_ai_model_custom_url_low_trust:
    client: false
    default: ''
  chatbot_open_ai_model_custom_api_type:
    client: false
    default: ''
  chatbot_open_ai_model_custom_api_version:
    client: false
    default: '2023-09-01-preview'
  chatbot_embeddings_enabled:
    default: false
    client: false
  chatbot_open_ai_embeddings_model:
    client: false
    type: enum
    default: text-embedding-ada-002
    choices:
      - text-embedding-ada-002
      - text-embedding-3-small
  chatbot_embeddings_strategy:
    default: benchmark_user
    client: false
    type: enum
    choices:
      - benchmark_user
      - categories
  chatbot_embeddings_benchmark_user_trust_level:
    client: false
    default: 1
    min: 0
    max: 4
  chatbot_embeddings_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  chatbot_open_ai_embeddings_char_limit:
    client: false
    default: 11500
  chatbot_open_ai_embeddings_model_custom_url:
    client: false
    default: ''
  chatbot_quick_access_talk_button:
    client: true
    default: chat
    type: enum
    choices:
      - "off"
      - chat
      - personal message
  chatbot_quick_access_bot_kicks_off:
    default: true
    client: true
  chatbot_quick_access_talk_button_bot_icon:
      client: true
      default: robot
  chatbot_include_inner_thoughts_in_private_messages:
    default: false
    client: false
  chatbot_can_trigger_from_whisper:
    default: false
    client: false
  chatbot_permitted_all_categories:
    default: true
    client: false
  chatbot_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  chatbot_auto_respond_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  chatbot_quota_high_trust:
    default: 100
    client: false
  chatbot_quota_medium_trust:
    default: 50
    client: false
  chatbot_quota_low_trust:
    default: 10
    client: false
  chatbot_max_look_behind:
    default: 5
    max: 160
    min: 1
    client: false
  chatbot_include_whispers_in_post_history:
    default: false
    client: false
  chatbot_strip_quotes:
    default: true
    client: false
  chatbot_support_vision:
    client: false
    default: false
  chatbot_open_ai_vision_model:
    client: false
    default: gpt-4-vision-preview
  chatbot_reply_job_time_delay:
    client: false
    default: 1
    min: 0
    max: 3
  chatbot_open_ai_token:
    client: false
    default: ''
  chatbot_request_temperature:
    client: false
    default: 100
    min: 0
    max: 100
  chatbot_request_top_p:
    client: false
    default: 100
    min: 0
    max: 100
  chatbot_request_frequency_penalty:
    client: false
    default: 0
    min: -200
    max: 200
  chatbot_request_presence_penalty:
    client: false
    default: 0
    min: -200
    max: 200
  chatbot_max_response_tokens:
    client: false
    default: 200
  chatbot_bot_user:
    client: true
    type: username
    default: Chatbot
  chatbot_forum_search_function_max_results:
    client: false
    default: 10
    max: 100
    min: 10
  chatbot_forum_search_function_similarity_threshold:
    client: false
    default: 0.8
    max: 1
    min: 0
  chatbot_forum_search_function_reranking_group_promotion:
    client: false
    type: group_list
    list_type: compact
    default: ""
    allow_any: false
    refresh: true
  chatbot_locations_plugin_support:
    client: false
    default: false
  chatbot_escalate_to_staff_function:
    client: false
    default: false
  chatbot_escalate_to_staff_groups:
    client: false
    type: group_list
    list_type: compact
    default: ""
    allow_any: false
    refresh: true
  chatbot_escalate_to_staff_max_history:
    client: false
    default: 10
  chatbot_news_api_token:
    client: false
    default: ''
  chatbot_serp_api_key:
    client: false
    default: ''
  chatbot_marketstack_key:
    client: false
    default: ''
  chatbot_enable_verbose_console_logging:
    client: false
    default: false
  chatbot_enable_verbose_rails_logging:
    client: false
    default: false
